require("mhcyr.plugins-setup")
require("mhcyr.core.options")
require("mhcyr.core.keymaps")
require("mhcyr.core.colorscheme")
require("mhcyr.plugins.nvim-tree")
require("mhcyr.plugins.lualine")
require("mhcyr.plugins.telescope")
require("mhcyr.plugins.nvim-cmp")
require("mhcyr.plugins.lsp.mason")

